# Generated by Django 2.2 on 2019-06-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190613_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='Descriprions',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
