# Generated by Django 2.2 on 2019-06-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190613_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.Ingredient'),
        ),
    ]
